/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         12000000U  /*!< Board xtal0 frequency in Hz */
#define BOARD_XTAL32K_CLK_HZ                          32768U  /*!< Board xtal32K frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************** Configuration BOARD_I2CBootClock ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_I2CBootClock configuration
 ******************************************************************************/
#define BOARD_I2CBOOTCLOCK_CORE_CLOCK               8000000U  /*!< Core clock frequency: 8000000Hz */


/*******************************************************************************
 * API for BOARD_I2CBootClock configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_I2CBootClock(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************* Configuration BOARD_UARTBootClock ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_UARTBootClock configuration
 ******************************************************************************/
#define BOARD_UARTBOOTCLOCK_CORE_CLOCK              8000000U  /*!< Core clock frequency: 8000000Hz */


/*******************************************************************************
 * API for BOARD_UARTBootClock configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_UARTBootClock(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

