/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: LPC810
package_id: LPC810M021FN8
mcu_data: ksdk2_0
processor_version: 7.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 4b00c524-a63f-4dfe-92ee-a1065f4615d3
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * I2C0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C0'
- type: 'lpc_i2c'
- mode: 'I2C_Transfer'
- custom_name_enabled: 'false'
- type_id: 'lpc_i2c_f5051a0134792729f1007113ec6ddccd'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'I2C0'
- config_sets:
  - fsl_transfer:
    - init_transfer: 'false'
    - slave_transfer_cfg:
      - init_rx_transfer: 'true'
      - rx_dataSize: '10'
      - init_tx_transfer: 'true'
      - tx_dataSize: '10'
  - transferCfg:
    - transfer:
      - init_callback: 'true'
      - callback_fcn: 'Eep_I2CHandleSlaveEvent'
      - user_data: ''
  - fsl_i2c:
    - i2c_mode: 'kI2C_Slave'
    - clockSource: 'FunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - i2c_slave_config:
      - enableSlave: 'true'
      - address0:
        - address: '0x20'
        - addressDisable: 'false'
        - qualMode: 'kI2C_QualModeMask'
        - qualAddress: '0'
      - address1:
        - address: '0'
        - addressDisable: 'true'
      - address2:
        - address: '0'
        - addressDisable: 'true'
      - address3:
        - address: '0'
        - addressDisable: 'true'
      - busSpeed: 'kI2C_SlaveStandardMode'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_slave_config_t I2C0_config = {
  .enableSlave = true,
  .address0 = {
    .address = 0x20,
    .addressDisable = false
  },
  .qualMode = kI2C_QualModeMask,
  .qualAddress = 0,
  .address1 = {
    .address = 0,
    .addressDisable = true
  },
  .address2 = {
    .address = 0,
    .addressDisable = true
  },
  .address3 = {
    .address = 0,
    .addressDisable = true
  },
  .busSpeed = kI2C_SlaveStandardMode
};
i2c_slave_handle_t I2C0_handle;

void I2C0_init(void) {
  /* Initialization function */
  I2C_SlaveInit(I2C0_PERIPHERAL, &I2C0_config, I2C0_CLOCK_SOURCE);
  I2C_SlaveTransferCreateHandle(I2C0_PERIPHERAL, &I2C0_handle, Eep_I2CHandleSlaveEvent, NULL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  I2C0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
