/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: LPC810
package_id: LPC810M021FN8
mcu_data: ksdk2_0
processor_version: 7.0.1
pin_labels:
- {pin_num: '3', pin_signal: SWCLK/PIO0_3, label: SCL, identifier: SCL}
- {pin_num: '4', pin_signal: SWDIO/PIO0_2, label: SDA, identifier: SDA}
- {pin_num: '2', pin_signal: PIO0_4, label: TXD, identifier: RDY_N}
- {pin_num: '5', pin_signal: PIO0_1/ACMP_I2/CLKIN, label: RDY_N, identifier: RDY_N}
- {pin_num: '8', pin_signal: PIO0_0/ACMP_I1, label: RXD}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_I2CInitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: I2C0, signal: SCL, pin_signal: SWCLK/PIO0_3, opendrain: enabled}
  - {pin_num: '4', peripheral: I2C0, signal: SDA, pin_signal: SWDIO/PIO0_2, opendrain: enabled}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/ACMP_I2/CLKIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_I2CInitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_I2CInitPins(void)
{
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);

    IOCON->PIO[6] = ((IOCON->PIO[6] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_OD_MASK)))

                     /* Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
                     | IOCON_PIO_OD(PIO0_2_OD_ENABLED));

    IOCON->PIO[5] = ((IOCON->PIO[5] &
                      /* Mask bits to zero which are setting */
                      (~(IOCON_PIO_OD_MASK)))

                     /* Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
                     | IOCON_PIO_OD(PIO0_3_OD_ENABLED));

    /* I2C1_SDA connect to P0_2 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C_SDA, kSWM_PortPin_P0_2);

    /* I2C1_SCL connect to P0_3 */
    SWM_SetMovablePinSelect(SWM0, kSWM_I2C_SCL, kSWM_PortPin_P0_3);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_UARTInitPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '8', peripheral: USART0, signal: RXD, pin_signal: PIO0_0/ACMP_I1}
  - {pin_num: '2', peripheral: USART0, signal: TXD, pin_signal: PIO0_4, identifier: ''}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/ACMP_I2/CLKIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_UARTInitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_UARTInitPins(void)
{
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);

    /* USART0_TXD connect to P0_4 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_4);

    /* USART0_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_0);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
