/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_2_OD_ENABLED 0x01u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_3_OD_ENABLED 0x01u

/*! @name PIO0_3 (number 3), SCL
  @{ */
#define BOARD_I2CINITPINS_SCL_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_SCL_PIN 3U /*!<@brief PIO0 GPIO pin index: 3 */
                                     /* @} */

/*! @name PIO0_2 (number 4), SDA
  @{ */
#define BOARD_I2CINITPINS_SDA_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_SDA_PIN 2U /*!<@brief PIO0 GPIO pin index: 2 */
                                     /* @} */

/*! @name PIO0_1 (number 5), RDY_N
  @{ */
#define BOARD_I2CINITPINS_RDY_N_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_I2CINITPINS_RDY_N_PORT 0U   /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_RDY_N_PIN 1U    /*!<@brief PIO0 GPIO pin index: 1 */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_I2CInitPins(void); /* Function assigned for the Cortex-M0P */

/*! @name PIO0_1 (number 5), RDY_N
  @{ */
#define BOARD_UARTINITPINS_RDY_N_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_UARTINITPINS_RDY_N_PORT 0U   /*!<@brief PORT device index: 0 */
#define BOARD_UARTINITPINS_RDY_N_PIN 1U    /*!<@brief PIO0 GPIO pin index: 1 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UARTInitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
