/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_2_OD_ENABLED 0x01u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_3_OD_ENABLED 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_4_MODE_PULL_UP 0x02u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_4_OD_ENABLED 0x01u

/*! @name PIO0_3 (number 3), I2C_SCL
  @{ */
#define BOARD_I2CINITPINS_I2C_SCL_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_I2C_SCL_PIN 3U /*!<@brief PIO0 GPIO pin index: 3 */
                                         /* @} */

/*! @name PIO0_2 (number 4), I2C_SDA
  @{ */
#define BOARD_I2CINITPINS_I2C_SDA_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_I2C_SDA_PIN 2U /*!<@brief PIO0 GPIO pin index: 2 */
                                         /* @} */

/*! @name PIO0_4 (number 2), I2C_RDY_N
  @{ */
#define BOARD_I2CINITPINS_I2C_RDY_N_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_I2CINITPINS_I2C_RDY_N_PORT 0U   /*!<@brief PORT device index: 0 */
#define BOARD_I2CINITPINS_I2C_RDY_N_PIN 4U    /*!<@brief PIO0 GPIO pin index: 4 */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_I2CInitPins(void); /* Function assigned for the Cortex-M0P */

/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_1_MODE_PULL_UP 0x02u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_1_OD_ENABLED 0x01u

/*! @name PIO0_0 (number 8), UART_RXD
  @{ */
#define BOARD_UARTINITPINS_UART_RXD_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_UARTINITPINS_UART_RXD_PIN 0U /*!<@brief PIO0 GPIO pin index: 0 */
                                           /* @} */

/*! @name PIO0_4 (number 2), I2C_RDY_N
  @{ */
#define BOARD_UARTINITPINS_UART_TXD_PORT 0U /*!<@brief PORT device index: 0 */
#define BOARD_UARTINITPINS_UART_TXD_PIN 4U /*!<@brief PIO0 GPIO pin index: 4 */
                                           /* @} */

/*! @name PIO0_1 (number 5), UART_RDY_N
  @{ */
#define BOARD_UARTINITPINS_UART_RDY_N_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_UARTINITPINS_UART_RDY_N_PORT 0U   /*!<@brief PORT device index: 0 */
#define BOARD_UARTINITPINS_UART_RDY_N_PIN 1U    /*!<@brief PIO0 GPIO pin index: 1 */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_UARTInitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
